apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhesion-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adhesion-deployment
  template:
    metadata:
      name: adhesion-deployment
      labels:
        app: adhesion-deployment
    spec:
      containers:
        - name: adhesion-deployment
          image: blackrock30/adhesion-service:1.1.3
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: adhesion-service
spec:
  selector:
    app: adhesion-deployment
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort