# adhesion-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhesion-service
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: adhesion-service
  template:
    metadata:
      labels:
        app: adhesion-service
    spec:
      containers:
        - name: adhesion-service
          image: blackrock30/adhesion-service:1.0.1
          ports:
            - containerPort: 9001

          env:
            - name: POSTGRES_HOST
              value: postgres-adhesion-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: adhesion_db
            - name: POSTGRES_USER
              value: adhesion_user
            - name: POSTGRES_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            - name: SPRING_DATASOURCE_USERNAME
              value: ${POSTGRES_USER}
            - name: SPRING_DATASOURCE_PASSWORD
              value: ${POSTGRES_PASSWORD}
          volumeMounts:
            - name: adhesion-service-persistent-storage  # Use the same PVC name you defined in the PVC manifest
              mountPath: /app/data  # Mount path within the container where data should be persisted
          volumes:
            - name: adhesion-service-persistent-storage  # Use the same PVC name you defined in the PVC manifest
              persistentVolumeClaim:
                claimName: postgres-adhesion-pvc

---

# adhesion-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adhesion-service-service
spec:
  selector:
    app: adhesion-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort
