apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhesion-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adhesion-deployment
  template:
    metadata:
      name: adhesion-deployment
      labels:
        app: adhesion-deployment
    spec:
      containers:
        - name: adhesion-deployment
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
          image: blackrock30/adhesion-service:1.0.2