apiVersion: v1
kind: Service
metadata:
  name: adhesion-service-svc
  labels:
    name: adhesion-service-svc
spec:
  ports:
    - targetPort: 9001
      port: 9001
      nodePort: 30163
      protocol: TCP
  selector:
    app: adhesion-deployment
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhesion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adhesion-deployment
  template:
    metadata:
      labels:
        app: adhesion-deployment
    spec:
      containers:
        - image: blackrock30/adhesion-service:1.0
          name: adhesion-deployment
          ports:
            - containerPort: 9001
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password

